version: 1.0.{build}
branches:
  only:
  - master
  - develop
image: Visual Studio 2017
configuration: release
platform: x64
environment:
  PYTHON: C:\Python35-x64
  PATH: C:\Program Files\Project\bin;C:\Program Files\Microsoft MPI\Bin;%PATH%
  AITHER_FLUID_DATABASE: C:\Program Files\Project\fluidDatabase
build_script:
- ps: >-
    powershell ci\appveyor\installMPI.ps1

    powershell ci\appveyor\buildAither.ps1
test_script:
- cmd: >-
    cd testCases

    %PYTHON%\python.exe regressionTests.py --mpirunPath=mpiexec.exe --aitherPath=aither.exe --operatingSystem=windows